### PR TITLE
add txtstyle params and re-implmenet numberFormat

### PR DESCRIPTION
**Pull request by WilliamCunhaCardoso**
Implementing issue: FormBuilderSlider Legends #342

This adds TextStyle params to min value, field value and max value.

This also re-implements number format on legend.

### CODE REVIEW

**Comment by danvick** [comment]
Thanks for your contribution @WilliamCunhaCardoso. You're the best.

**Comment by danvick** [comment]
Could you consider renaming `fieldTextStyle` to just `textStyle` and having it as the default style for all in case `minTextStyle` and `maxTextStyle` are not defined? 

This would make it easy for someone who'd like to have current value, min, and max to have the same style to define it just once.

**Comment by WilliamCunhaCardoso** [comment]
> Could you consider renaming `fieldTextStyle` to just `textStyle` and having it as the default style for all in case `minTextStyle` and `maxTextStyle` are not defined?
> 
> This would make it easy for someone who'd like to have current value, min, and max to have the same style to define it just once.

Sure!! I'll work on it

**Comment by WilliamCunhaCardoso** [comment]
Is this approach okay?

**Comment by danvick** [comment]
Great!

**Pull request merged**
