### PR TITLE
Adds FormBuilderSearchableDropdown to the project.

### PR DESCRIPTION
**Pull request by lferrerad**
As the dropdown_search is already in nullsafety, I returned it to the project with the necessary changes to work.

### CODE REVIEW

**Comment by ashim-k-saha** [comment]
Hi, @danvick any plan to merge this PR?

**Comment by listepo** [comment]
looks like a separate package

**Comment by kenzomartins** [comment]
Hi @danvick, is there an eta to merge this PR?

**Comment by danvick** [comment]
Hi @lferrerad / @listepo / @kenzomartins / @ashim-k-saha 

Thanks for your PR @lferrerad and sorry for the lateness of response.

Null-safety did expose a major flaw of this package in that we have been so dependent on external packages, some of which aren't being actively maintained. 
In the past, I've had to submit PRs to other repos after issues are raised in this repo about issues emanating from the dependencies; but with null-safety, this wasn't remotely possible.

This made us rethink the package. We decided to remove all fields with external dependencies from the package.

Not to worry though, the plan is to split up the package into separate packages but we'll end up with all fields we had initially - as long as the dependencies are properly maintained.
As of ~7.0.0, we'll have these packages:
 - [flutter_form_builder](https://pub.dev/packages/flutter_form_builder/versions/7.0.0-alpha.2): the core packages with fundamental building blocks
 - [form_builder_validators](https://pub.dev/packages/form_builder_validators) - for validation
 - [form_builder_fields](https://pub.dev/packages/form_builder_fields) - common fields that are native to flutter
 - [form_builder_extra_fields](https://pub.dev/packages/form_builder_extra_fields) - additional fields that depend on external packages (such as your beloved FormBuilderSearchableDropdown)

**Pull request closed without merging**
