### PR TITLE
Upgrade datetime_picker_formfield to 0.3.2

### PR DESCRIPTION
**Pull request by knaeckeKami**
datetime_picker_formfield made some breaking changes, but introduced important bug fixes.
This PR updates to datetime_picker_formfield 0.3.2 and implement some changes to address these breaking changes without changing the API of this library; With one exception: 
Since InputType was deleted from datetime_picker_formfield, I introduce a new enum InputType with the same values.

### CODE REVIEW

**Comment by danvick** [comment]
Thanks for your contribution @knaeckeKami. Will review and publish as soon as I can.

**Comment by danvick** [comment]
That'll be helpful. I've also realized that the current version you've added is using the new version v1.7 of Flutter which has breaking changes. 

That'll also require that I work on making the whole package compatible with this version of Flutter.

**Comment by knaeckeKami** [comment]
Oh, I'm already on (1.7.8+hotfix.3) so I didn't realize, sorry. 
But for my use cases, flutter_form_builder with the new datetime_picker_formfield works without problems on flutter 1.7.8, I didn't notice any breaking changes. I didn't test if it still works on flutter 1.5.4. 
Which problems do have have specifically?

**Comment by danvick** [comment]
There was [this issue](https://github.com/danvick/flutter_form_builder/issues/91) reported by some individuals who did the upgrade recently. 

Problem is that I cant easily switch between versions of Flutter, and I'm working on some work projects which aren't compatible with the v1.7.8

**Comment by knaeckeKami** [comment]
I'm not sure if it's related to flutter 1.7.8. reset() works fine for me.

Would be nice to have a minimal sample where this bug occurs.

**Comment by danvick** [comment]
If you could find time to assist in resolving the issue for them I'll appreciate, we can ask whoever raised the issue to give clarification.
I've also been unable to reproduce the error.

**Pull request merged**
