### PR TITLE
fix #1019

### LINKED ISSUE #1019: [flutter_form_builder] Calls FormBuilder.onChanged when it has no changes
I test this behaviour in Flutter `Form` widget and works as expected

Expected behaviour:
When focusing into FormBuilderField without changes, don't call FormBuilder.onChanged

Actual behaviour: 
When focusing into FormBuilderField without changes, calls FormBuilder.onChanged

Steps to reproduce:

1. Focus in a FormField (ex: FormBuilderTextField)
3. Error: Calls FormBuilder.onChanged

flutter_form_builder version: `7.1.1`
Device: MacOS - Chrome

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Form code sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatefulWidget(),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  final _formBuilderKey = GlobalKey<FormBuilderState>();
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Form(
          key: _formKey,
          onChanged: () {
            print('Form changed');
          },
          child: FocusTraversalGroup(
            policy: WidgetOrderTraversalPolicy(),
            child: TextField(
              decoration: const InputDecoration(labelText: 'Text'),
              onChanged: (String? value) => print('FormText changed: $value'),
            ),
          ),
        ),
        FormBuilder(
          key: _formBuilderKey,
          onChanged: () {
            print(
                'FormBuilder changed/Instant value: ${_formBuilderKey.currentState?.instantValue}');
          },
          child: FormBuilderTextField(
            name: 'text',
            decoration: const InputDecoration(labelText: 'Text'),
            onChanged: (String? value) =>
                print('FormBuilderText changed: $value'),
          ),
        ),
      ],
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by ipcjs**
## Connection with issue(s)

Resolve issue #1019 
Close #1019 

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [ ] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by ipcjs** [comment]
Well, I moved the code that falls back to the empty string to the `_handleControllerChanged` function, which should cover all cases.🤔

**Comment by deandreamatias** [comment]
@ipcjs this fix the issue #1019 ?
Can you add some evidence or test to verify this?

**Comment by ipcjs** [comment]
Ok, I added the test code.🙂

**Comment by deandreamatias** [comment]
Thanks @ipcjs, but I'm not sure if this PR solve the issue #1019 
How this pr solve this issue?

**Comment by ipcjs** [comment]
`_effectiveController.text` is non-null and `value` is nullable.
If no initial value is set, the value of `value` is null and the value of `_effectiveController.text` is an empty string, which are not equal, the `onChanged` callback will be triggered eventually.
Using `value ? ''` can prevent the callback from being triggered.

**Comment by deandreamatias** [comment]
OK I understand now. Thanks for your detail answer and patience

**Pull request merged**
