### PR TITLE
added key to text_field, checkbox, checkbox_list

### PR DESCRIPTION
**Pull request by zaralockheart**
Hi, thanks for this superb library. It helps a lot in building a form, especially a sophisticated one!

However, I might want to add something that seems pretty useful (I guess) which is using key from the attribute for widget testing.

I've added Key to these three fields
`FormBuilderTextField`,
`FormBuilderCheckbox`,
`FormBuilderCheckboxList`

Also, I added widget test for example for those who may find it beneficial.

### CODE REVIEW

**Comment by zaralockheart** [comment]
this could be helpful for #155 but I will add integration test will flutter_driver whenever I am free later.

**Comment by zaralockheart** [comment]
also #151

**Comment by danvick** [comment]
Hi @yuzurih4,
I'm not an expert on Widget testing. 
I've realized you've wrapped the fields in a `Container` and added `Key`s to them. 
Since the fields already have `GlobalKey`s that identify them, is it possible to use these already available `GlobalKey`s instead of creating another key?
So that instead of having `final nameInputField = find.byKey(Key('name'));`, we have `final nameInputField = find.byKey(GlobalKey('name'));`?

**Comment by yuzurih4** [comment]
Ahh I see, let me try with that and see if this PR is still valid. Thanks for pointing it out :)

**Comment by yuzurih4** [comment]
Hi @danvick,

Actually I am not an expect on Widget testing too, but my finding is I can't use `GlobalKey` since `GlobalKey` comes with short hash.

With `final nameInputField = find.byKey(GlobalKey(debugLabel: 'name'));` I get error like 
```
  Expected: exactly one matching node in the widget tree
  Actual: ?:<zero widgets with key [GlobalKey#9aa62 name] (ignoring offstage widgets)>
   Which: means none were found but one was expected
```

**Comment by shashikantshaale** [comment]
Duplicate of #184

**Comment by zaralockheart** [comment]
@shashikantshaale ahhh I see that you add key argument, I am trying to reuse the name as the key. Alright, I'll close this.

**Comment by danvick** [comment]
Hi @zaralockheart,
Your contribution is still highly appreciated. 
You guys are making my work easier.

**Pull request closed without merging**
