### PR TITLE
Method to update typeahead label for custom datamodel

### PR DESCRIPTION
**Pull request by JohnKuan**
add a method to allow better control of text update to the in-build TextEditingController

### CODE REVIEW

**Comment by danvick** [comment]
Hi @JohnKuan,
Thanks for your contribution. 
This is something that has been requested for quite a while.
I'll have a look to review the changes before merging and let you know if any action is needed.

Have a good one.
Cheers!

**Comment by JohnKuan** [comment]
Sure @danvick.

**Comment by danvick** [comment]
Hi @JohnKuan,
I love your implementation of this feature. I've fixed a few issues including the assertion for type checking. 
How do you like changing `onSuggestionSelectedLabel` to a more intuitive (IMO) `selectionToTextTransformer`?

**Comment by JohnKuan** [comment]
Hi @danvick,

I just saw your merge. Thank you for fixing the issues on the type assertion.

I also noticed you removed the `onSuggestionSelected` field from the params. I actually do have a use for it, which is separated from populating the `textfieldcontroller.text`. I tried to utilised the `selectionToTextTransformer` field but it resulted in an infinite init loop on my use case. Would it okay to restore that field?

**Comment by danvick** [comment]
Hello @JohnKuan,
I apologize for removing the field, I'll work to restore it ASAP. I had realized that I wasn't using it initially, that's why I had it removed. 
I'll be rolling out v3.5.2 in a few which will contain the fix; I'll let you know when I do.

**Comment by danvick** [comment]
Now about this infinite loop, is it something that's caused by the changes I had introduced? Can I have the sample code that causes this?

**Comment by danvick** [comment]
3.5.2 is published.

**Pull request merged**
