### PR TITLE
Made FormBuilderField non-abstract to allow creating custom input fields

### PR DESCRIPTION
**Pull request by danvick**
If `FormBuilderField` is abstract, it can't be used to create a custom field type as we've claimed in README

### CODE REVIEW

**Comment by danvick** [comment]
Another solution would be to have it abstract as it was and create a separate class to be used to create custom fields - like a `FormBuilderCustomField` as we had in v3

**Comment by awhitford** [comment]
If the class is expected to be used directly, then obviously drop the `abstract` keyword.  I thought the _expectation_ was to subclass, just like all of the built-in fields, so adding the keyword was like an indicator telling people what to do.

I apologize for the confusion.

Ideally there is a test case for creating a custom field that serves as a reference.

**Comment by awhitford** [comment]
I made two tweaks to the example:
* Specify the type to be type safe
* Variables with underscores should be reserved for class level properties.

**Comment by danvick** [comment]
After the changes have been made, will it now be safe to merge into master?

**Pull request merged**
