### PR TITLE
Fix example project

### PR DESCRIPTION
**Pull request by prasadsunny1**
- Migrate to androidX.
- Upgrade gradle version.
- Update target android sdk

### CODE REVIEW

**Comment by danvick** [comment]
Thanks for the PR, @prasadsunny1. You're the best.

**Comment by prasadsunny1** [comment]
Wow, my first PR.
Thanks for accepting.
BTW, love your project.

**Comment by prasadsunny1** [comment]
Is it ok to pump up the Gradle version to the latest one?
(I don't understand android that well, expert advice? !!)

**Comment by danvick** [comment]
This package doesn't rely on any android specific code, so it should be safe. 
PS: I'm not an Android expert either. ;-)
Thanks for the love.

**Pull request merged**
