### PR TITLE
Release candidate for [3.14.0-alpha.4]: fix build for Flutter Web >=1.21.0-9.1.pre

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MikeTemnokhud** [comment]
@danvick @vin-fandemand Please, merge this PR. Without this code changes, your package will not work on Flutter 1.21+

**Comment by danvick** [comment]
Thanks for your contribution. And sorry for the delays, I haven't had enough time to work on this repo.

**Comment by MichaelDark** [comment]
@danvick could you please publish it like `3.14.0-alpha.4`?

**Comment by danvick** [comment]
Sorry for the delays guys, `3.14.0-alpha.4` has been published

**Pull request merged**
