### PR TITLE
Portuguese language added

### PR DESCRIPTION
**Pull request by YuenEsc**
Hi Danvick, I added the portuguese support for the library

### CODE REVIEW

**Comment by danvick** [comment]
Hello @YuenEsc,
Thanks for contributing. Would you mind adding Portuguese to the supported languages in `FormBuilderLocalizations.isSupported` function before we merge this PR? The function should be on line [131](https://github.com/YuenEsc/flutter_form_builder/blob/0dc65698a31a98dbb5ef21e108f7cf7e3fffb740/lib/localization/form_builder_localizations.dart#L131)

**Comment by danvick** [comment]
Also, don't forget to run `flutter format lib` to ensure that the code is well-formatted so as to avoid failing CI builds.

@awhitford is there a way we could ignore formatting for the `l10n` directory since that's mostly autogenerated code?
I think the solution is to move the `l10n` directory out of the `lib` directory to the project root, isn't that so?

**Comment by awhitford** [comment]
@danvick The `flutter format` does not have an _exclude directory_ feature. https://github.com/dart-lang/dart_style/issues/864

**Can we not simply expect folks to run `flutter format` on the `l10n` generated code before checking it in?**  (A bunch suggest this.)

Another suggestion is to run `flutter format` on the `l10n` directory.  However, I really don't like this idea because that means that the code being used won't exactly match what is committed, and that could lead to some confusing debugging.

The third suggestion (yours) is to move the `l10n` directory out of `lib`, and then explicitly calling `flutter format lib example` instead of `flutter format .` The `l10n` directory _must only contain generated code_ -- but there is not a good way to enforce this.  (Ironic that FFB has a `localization` directory as well as a `l10n` directory.)

**Comment by YuenEsc** [comment]
Yeah sorry I do it as soon as possible and then I deploy it thanks

**Comment by YuenEsc** [comment]
I have added pt as you requested, and also I ran the format command. Hope it's now all right. I will wait for your feedback

**Pull request merged**
