### PR TITLE
Refactor to support a common FormBuilderField class.

### LINKED ISSUE #511: readOnly vs enabled
I stumbled across this:
https://github.com/danvick/flutter_form_builder/blob/32df12649ba22a2b7d006290ad09e7164fd2a724/lib/src/fields/form_builder_text_field.dart#L138

😲 State variables should not be set in the `build` method.  State variable manipulation should be confined to `initState` and `setState`.  The `_readOnly` variable should simply be a local variable to the method; there is no need to add this to the `State` class.

🤦 It appears that this is copied/pasted for every field.

So this leads me to ponder...

For a _Form Field_, what is the difference between `readOnly` and `enabled`?  Because it looks like `enabled` is just `!readOnly`. If that is the case, could we remove `readOnly` and simply imply it based on `!enabled`? 🤯 

In fact, consider this example:
https://github.com/danvick/flutter_form_builder/blob/32df12649ba22a2b7d006290ad09e7164fd2a724/lib/src/fields/form_builder_checkbox_group.dart#L6-L14
The class has both `readOnly` and `enabled`, but `enabled` isn't really used, and the `enabled` value for the `FormField` is just `enabled: !_readOnly`.

Since `enabled` is an established Flutter Form concept, I suggest `readOnly` be _deprecated_ in favor of using `enabled` if they are truly just equal and opposite.

### PR DESCRIPTION
**Pull request by awhitford**
* Ensured that each field supports `enabled`, independent of `readOnly` since these are two separate ideas.
* Added `autovalidateMode` property across fields. 
* Saved hundreds of lines of code by avoiding copy/paste duplication across classes.
* Removed code that set `_readOnly` during `build()`. Resolves #511 
* Reviewed and improved type constraints, making the code more type safe.

### CODE REVIEW

**Comment by awhitford** [comment]
🎃 Happy Halloween!
👻 Nothing says _scary_ like a pull request for a radical refactoring.

**Comment by danvick** [comment]
> 🎃 Happy Halloween!
> 👻 Nothing says _scary_ like a pull request for a radical refactoring.

Hahaha. Nice!

**Comment by danvick** [comment]
I like what you've done with the place - CI, Code coverage and all.

**Comment by danvick** [comment]
Hi @awhitford,
I would appreciate your feedback before I merge version_4 into master and continue with the release.

I don't know about you but supporting both versions in parallel has been hectic for me.

**Comment by awhitford** [comment]
I should have pointed out that there was a **breaking change** introduced for `FormBuilderCustomField` where `formField` was replaced by its `builder`.  This was done to avoid duplicating elements like `enabled` and `autovalidateMode`.  It looks like you did something similar in `version_4`.

I will take a closer look at your `version_4` branch. I actually didn't realize how far along you were on this.  How would you prefer to receive feedback?  Just PRs?

**Comment by danvick** [comment]
I see. Then we'd rather hold off the changes to v3 then.

Yeah, the uptake of version v4 has been surprisingly faster than I thought and the feedback prompt. 
I'd like to think it has been quite well tested in the wild, I also had migrated to prerelease versions in some of my projects.

I would actually prefer a more direct channel between me and you if you don't mind.

**Comment by awhitford** [comment]
> I would actually prefer a more direct channel between me and you if you don't mind.

Would you be interested in creating a Gitter Community for Flutter_Form_Builder?  Then we could create a Room for version4 and collaborate there.

Or do you have a better idea?

**Comment by awhitford** [comment]
I am **REVERTING this because** I think this **radical change** should simply **be part of v4**.

**Pull request merged**
