### PR TITLE
Exporting the class TextFieldProps from dropdown_search.dart

### PR DESCRIPTION
**Pull request by moazelsawaf**
While importing the file form_builder_searchable_dropdown.dart, the class TextFieldProps from dropdown_search/dropdown_search.dart is not imported with it, which forces for manual import in order to customize the Search Box inside the SelectionWidget.

In the commit, I have just exported the class from the file form_builder_searchable_dropdown.dart to eliminate the problem I have described.

### CODE REVIEW

**Comment by danvick** [comment]
Hi @moazelsawaf, thanks for contributing. 

Would you consider moving the export to `packages/form_builder_extra_fields/lib/form_builder_extra_fields.dart`.

We prefer having all the exports in one barrel file.

**Comment by moazelsawaf** [comment]
Done moving the export.

**Comment by danvick** [comment]
Thanks for your contribution @moazelsawaf

**Comment by moazelsawaf** [comment]
You are always welcome ❤

**Pull request merged**
