### PR TITLE
Implement shouldRequestFocus

### PR DESCRIPTION
**Pull request by WilliamCunhaCardoso**
This mandatory request focus embarrass forms which are able to scroll. I've implemented an optional attribute, so we can decide whether an option should request focus.

Also fixes issue from https://github.com/danvick/flutter_form_builder/issues/880

Also, I took the opportunity to order attributes and update imports.

Implemented on: 
- ChoiceChips;
- FilterChips;
- RadioGroup;
- Checkbox;

### CODE REVIEW

**Review by joaopereirajp — APPROVED** [review]

**Comment by WilliamCunhaCardoso** [comment]
@danvick Hi :) can you take a look on it when you have free time? Hope you are good

**Comment by cedricDevWP** [comment]
solve the problems #882 ?

**Comment by WilliamCunhaCardoso** [comment]
> solve the problems #882 ?

Done. Can check on https://github.com/danvick/flutter_form_builder/pull/881/commits/86e8f55b8ee36f4871b49dbf4d3ad34aab6285ed

**Comment by thedonatic** [comment]
#921

**Comment by thedonatic** [comment]
i also faced this issue in #921. Any status, when this pr will be merged.

**Comment by iamrohitsuthar** [comment]
@danvick Any update, when this PR will be merged?
or any other solution to this issue #921

**Comment by hareendranmg** [comment]
@danvick @WilliamCunhaCardoso Any update?

**Comment by WilliamCunhaCardoso** [comment]
> @danvick @WilliamCunhaCardoso Any update?

I am waiting for this repo owner some response. Till tho I will keep supporting this pr since I really need such implementation.

**Comment by SM2DevLLC** [comment]
Any update on when this will be merged? This is kind of a big issue.

**Comment by danvick** [comment]
Sorry for the delay guys. Haven't had time recently to work on this repo. Thanks for your contribution @WilliamCunhaCardoso et al

**Comment by SM2DevLLC** [comment]
@danvick It looks like this worked, but it doesn't seem like it was implemented for `FormBuilderCheckboxGroup`.

**Pull request merged**
